export const productList = [
  {
    name: "Great Dummy",
    slug: "great-dummy",
    price: 104.99,
    excerpt: "Something that you truly need, but haven’t known about it yet",
    image: "[https://dummyimage.com/500x400](https://dummyimage.com/500x400)",
    description: "Something that you truly need, but haven’t known about it yet.",
    tag: "classic",
  },
  {
    name: "Dummy X Pro",
    slug: "dummy-x-pro",
    price: 149.99,
    excerpt: "Something that you truly need, but haven’t known about it yet",
    image: "[https://dummyimage.com/500x400](https://dummyimage.com/500x400)",
    description: "Something that you truly need, but haven’t known about it yet.",
    tag: "master",
  },
  {
    name: "Wooden Dummy",
    slug: "wooden-dummy",
    price: 104.99,
    excerpt: "Something that you truly need, but haven’t known about it yet",
    image: "[https://dummyimage.com/500x400](https://dummyimage.com/500x400)",
    description: "Something that you truly need, but haven’t known about it yet.",
    tag: "classic",
  },
  {
    name: "Wooden X Pro",
    slug: "wooden-x-pro",
    price: 149.99,
    excerpt: "Something that you truly need, but haven’t known about it yet",
    image: "[https://dummyimage.com/500x400](https://dummyimage.com/500x400)",
    description: "Something that you truly need, but haven’t known about it yet.",
    tag: "master",
  },
  {
    name: "Basic Dummy",
    slug: "basic-dummy",
    price: 104.99,
    excerpt: "Something that you truly need, but haven’t known about it yet",
    image: "[https://dummyimage.com/500x400](https://dummyimage.com/500x400)",
    description: "Something that you truly need, but haven’t known about it yet.",
    tag: "classic",
  },
  {
    name: "Basic X Pro",
    slug: "basic-x-pro",
    price: 149.99,
    excerpt: "Something that you truly need, but haven’t known about it yet",
    image: "[https://dummyimage.com/500x400](https://dummyimage.com/500x400)",
    description: "Something that you truly need, but haven’t known about it yet.",
    tag: "master",
  },
]
